extends Node

enum UI {
	DISABLE_ALL_ACTION_PANELS,
	ENABLE_PANEL,
	CLEAR_FOCUSED_PANEL,
	SHOW_AND_POSITION_SELECTION_CURSOR,
	CLEAR_ALL_SELECTION_CURSORS,
	SHOW_AND_POSITION_ACTOR_POINTER,
	CLEAR_ALL_ACTOR_POINTERS,
}
